spring.application.name=food-identity
app.security.admin=admin
app.security.user=user
app.security.password=$2a$10$D0cXnF.5YxgXGmBapVHcSeMmcRpxHWYmFm87xYhA./gmMaOneTuya
app.security.secret=my-super-secret-key-that-is-long-enough-1234567890!@#

# Database Connection
spring.datasource.url=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=update

