spring.application.name=food-identity
app.security.admin=admin
app.security.user=user
app.security.password=$2a$10$D0cXnF.5YxgXGmBapVHcSeMmcRpxHWYmFm87xYhA./gmMaOneTuya
app.security.secret=my-super-secret-key-that-is-long-enough-1234567890!@#
server.port=8081

