spring.application.name=food-identity
spring.config.import=optional:file:.env[.properties]
app.security.admin=${APP_SECURITY_ADMIN}
app.security.user=${APP_SECURITY_USER}
app.security.password=${APP_SECURITY_PASSWORD}
app.security.secret=${APP_SECURITY_SECRET}

